### ISSUE TITLE
Enable vsync

### ISSUE THREAD

**Issue by yohannd1** [ItaloDoArbusto/Flappy#19]
As far as I know, vsync allows the game to be more accurately synchronized with the screen's refresh rate.
I kind of know how to enable vsync on pygame already, but it's going to cause problems with `DeltaTime`.

**Comment by ExtraMobs** [comment]
(Vou me comunicar em português porque quero ser direto e claro)

Não é garantido ter o VSync ativo, só com a tela escalada ou com a flag do OPENGL.

Quanto ao deltatime, basta dar Clock.tick(), vazio sem framerate que ele conta o intervalo entre os ticks sem pausar a tela.

**Comment by yohannd1** [comment]
Hmm. Um dia desses eu tava dando uma olhada e aparentemente um dos problemas é que o pygame.Clock usa uma função baseada em milisegundos e por causa disso um pouco de precisão é perdida, e o framerate não fica muito bem sincronizado. Eu até tentei usar as funções de tempo built-in do python mas não funcionou. Vou tentar de novo em breve.

**Comment by ExtraMobs** [comment]
a precisão perdida é realmente relevante? Eu acho que tu perderia mais se fosse em segundos por causa da imprecisão que os cálculos floats têm.

**Comment by yohannd1** [comment]
Bem, eu estou usando `time.time_ns`, que retorna um número inteiro (em nanosegundos), então floats não são o problema. Agora dito isso, eu não sei se essa precisão perdida por usar só milisegundos realmente é o problema. Mas preciso testar isso pra saber.

**Comment by ExtraMobs** [comment]
@YohananDiamond eu acho isso desnecessário, você vai gastar tempo demais pra obter prováveis milésimos de diferença, isso pra no final não impactar significativamente. Se você acha uma boa ideia colocar o VSync coloca, eu sempre pensei no VSync como algo preguiçoso que quando eu queria alterar alguma config em muitos dos jogos, eles só tinham o VSync pra regular o fps, e eu querendo alcançar limites de 40 FPS para minha máquina aguentar de maneira mais suave. Além de que no pygame não é garantido, MAS CONTUDO, eu acho a ideia interessante, tem meu apoio pra tentar.

**Comment by yohannd1** [comment]
Tentei mais uma vez aqui (https://github.com/italoseara/Flappy/commit/bdefd532655a8daf9cd575132c2f0e0e2bb99ca2) e acabei não conseguindo. Não sei exatamente o que está acontecendo de errado mas acho que não vou mais esquentar muito a cabeça com isso.
(Also, acabei por tornar o DeltaTime em uma variável e botar no state do jogo já que ela era basicamente isso, com um getter e um setter)

**Comment by ExtraMobs** [comment]
Como é dito na documentação do Pygame, isso pode não funcionar, não é garantido, só com FLAGS na tela específicas (SCALED, FULLSCREEN), e ainda sim provavelmente não funciona.
