### ISSUE TITLE
Generic Backend

### ISSUE THREAD

**Issue by yohannd1** [ItaloDoArbusto/Flappy#8]
`pygame` is kinda weird. I'd like to make a generic version of the game backend, and then add Pygame and SDL support for it. Not sure on how hard this would be to implement.

- [ ] Make a `Backend` class.
- [ ] Make a `PygameBackend(Backend)` class.

**Comment by yohannd1** [comment]
After thinking for some time I realized that pygame is already an abstraction layer. Maybe making another wrapper on top of it will make things slower and more complicated. If I really want to do this I might just start from scratch, and I don't think I want to do that in this specific project.

If I ever change my mind on this I'll reopen this.

**Comment by ExtraMobs** [comment]
Eu estava produzindo um backend pra widgets, claro que era pra um projeto pessoal meu, mas ainda sim obtive um bom progresso fazendo, por exemplo, um Edittext, só que desisti da ideia, pq apesar de facilitar E MUITO a produção de qualquer aplicação, é muito trabalhoso fazer, então para o meu projeto eu decidi migrar para Kivy, ao invés de Pygame.
